CREATE TABLE [dbo].[OrderHistory]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Type] SMALLINT NOT NULL DEFAULT 0,
	[Cups] INT NOT NULL,
	[CashGiven] DECIMAL(10, 2) NOT NULL,
	[Change] DECIMAL(10, 2) NOT NULL,
	[Occurred] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
)
